<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Login</title>
</head>
<body>
    <div class="container"> 
        <div class="jumbotron">
            <h2 class="text-center text-info">Login Form in PHP with Validation</h2>
        </div>
        <?php if (isset($auth_error)): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?= $auth_error ?>
            </div>
        <?php endif ?>
        <p>Veuillez remplir tous les champs</p>
        <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <table>
            <tr class="form-group ">
               <td> <label>Email</label></td>
                <td><input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" maxlength="50" required=""></td>
                <td><span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span></td>
            </tr>
            <tr class="form-group"></td>
                <td><label>Password</label></td>
                <td><input type="password" name="pwd" class="form-control" value="" required=""></td>
                <td><span class="text-danger"><?php if (isset($pwd_error)) echo $pwd_error; ?></span>
            </tr>  
            <tr>
                <td><input name="chk" type="checkbox"> Employé ?</td>
                <td><input type="submit" class="btn btn-primary" name="login" value="submit"></td>
                
            </tr>
            <tr><td>S'inscrire ? <a href="signup.php" class="mt-3">Click Here</a></td></tr>
        </form>
        <table>
    </div>
</body>
</html>